file_format: "1"
id: reviung5
name: REVIUNG5
type: shield
url: https://github.com/gtips/reviung/tree/master/reviung5
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - encoder
  - underglow